id: P001682
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17743
  title: ལུང་སྟོན་པ་ཙནྡྲ་པའི་མདོ།
  author: ''
  volumes:
    4c19ae414b214cb2812be2a91557af33:
      image_group_id: I8LS17762
      title: ''
      volume_number: 1
      total_pages: 1192
